# basic options
title: Welcome To My Website
author: Leo Munoz
email: S3812831@student.rmit.edu.au
description: A wonderful site
twitter_username: N/A
github_username:  LeoM-RMIT

# Build settings
markdown: kramdown
theme: minima
