# basic options
title: LM Websit RMIT
author: Leo Munoz
email: S3812831@student.rmit.edu.au
description: "Until computers and robots make quantum advances,
they basically remain adding machines capable only of doing things
in which all the variables are controlled and predictable. - Michio Kaku"

github_username:  LeoM-RMIT

# Build settings
markdown: kramdown
theme: minima
